### ISSUE TITLE
Not able to run the file given.

### ISSUE THREAD

**Issue by nitinEd** [davidthornton/chromedriver-2.31#1]
hello,

I have tried to run the code with your chrome driver file. I got an error "It's not an executable". I do not know how to convert into a binary file. If you can guide me that would be great. 

Thank You

**Comment by davidthornton** [comment]
Hi,

What system were you attempting to run this binary on. I compiled it for `linux_64` as per Google's instructions, so if your system is different you might experience an error like the one you mentioned.

**Comment by nitinEd** [comment]
Hi,

I am using Ubuntu 16.04.2 on hosted on AWS. It's linux_64 only. I am using Java 1.8 here.

**Comment by davidthornton** [comment]
Are you calling ChromeDriver from selenium correctly, then?

I'm using Python with headless chrome 59 and selenium - but I'm not aware if you can use a different library to selenium (with this driver and headless chrome)

**Comment by nitinEd** [comment]
I am using Selenium 3.4.0 with Java and Chrome 59.0 with the headless mode.

**Comment by davidthornton** [comment]
Hmm, are you setting the path to ChromeDriver correctly? It may be trying to execute another file (and throwing that error) alternatively - it might not matter but what architecture are your vCPUs powered by (x86, amd, arm... etc.?)

I compiled on x86, and I'm running docker containers so who knows what is virtualised at runtime (lol)

**Comment by nitinEd** [comment]
Paths are correct. I have cross checked it twice. There was another option people have mentioned it in threads that is compile the Chromedriver with  'use_ozone=true' build flag. Do you have any idea about this?

**Comment by davidthornton** [comment]
Hmm, I followed the instructions in this Dockerfile (manually, without Docker) https://gist.github.com/tabiodun/e4204ab83b3b7cfd2d28b478cf441162 which doesn't make use of that flag, but I understand that the patch committed to the codebase did use ozone instead of xvbf. So that may already be "done".

Apart from that, I'm pretty out of ideas! I will however be publishing a whole Docker image based on Debian or ubuntu with headless chrome installed soon. (And probably one with a purging API connected to it as well)

Can you use docker? If so, I highly recommend this image 😀

**Comment by nitinEd** [comment]
It worked finally!! The file didn't have execution permissions. Thank you for patience!
